import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './pages/components/header'
import Background from './pages/components/background'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body
        className={`${inter.className} min-h-screen bg-gradient-to-b from-blue-500 to-black-100`}
      >
        <Background />
        <main className="absolute min-h-full min-w-full">
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
